### ISSUE TITLE
New ExpressCheckout token errors when using permissions API

### ISSUE THREAD

**Issue by nathanwelch** [paypal/merchant-sdk-php#101]
## Question
Has anything changed recently for EC when using a 3rd party's token obtained through the permissions API which would cause error code 10409?

## Background
We use the Permissions API to connect other people's PayPal accounts to our app and then we process ExpressCheckout transactions on our site so the connected account receives the funds directly. We've been doing this approach for about a year now with no issues. 

## Issue
Today we started receiving this error when processing any PayPal EC transaction: **"You're not authorized to access this info. Express Checkout token was issued for a merchant account other than yours."** This is error code 10409. We generate our credentials with the token/secret from the connected account like this:
```
$cred = new PPSignatureCredential(PAYPAL_API_USERNAME, PAYPAL_API_PASSWORD, PAYPAL_API_SIGNATURE);
$cred->setApplicationId(PAYPAL_APP_ID);
$cred->setThirdPartyAuthorization(new PPTokenAuthorization($token, $secret));
```

We have not updated any of our code, composer packages, or account information. Our account is in good standing and so are the accounts which are connected to ours. We started receiving reports of user errors before PayPal transactions completely stopped on our site which further points to some issue/change on PayPal's side that had not rolled out all the way when users were initially impacted. 

Thanks for any help or insight you can give!

**Comment by pp-randy** [comment]
@nathanwelch To me this error would indicate that the permission token wasn't picked up in the DoExpressCheckout call, but that wouldn't make sense if your integration hasn't changed. Can you provide a correlation id from an API response and I will try to track down whats going on?  

Since this is payment impacting can you also reach out to PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask/ ?

**Comment by nathanwelch** [comment]
@pp-randy Thanks for the info and quick reply. Here's a correlation ID from a request I just made with an account that is in good standing: 53990bebaed1d

**Comment by nathanwelch** [comment]
Also Randy, if no API version is specified in an API call, does it default to the latest one or does it default to the oldest supported version? If it defaults to an older, but still supported, version, is it possible that an old API version that we were inadvertently using was fully deprecated recently which would have forced us to a new version?

**Comment by pp-randy** [comment]
@nathanwelch the version is showing 106 which should be fine for permissions.  Did you get that Technical Support ticket created?  I don't see anything standing out, the permission relationship looks ok to me.

**Comment by nathanwelch** [comment]
I created it just now: 160210-000166. I can try with a newer version of the API and see what happens. 

Would it be useful to see correlation IDs from requests at every step of the EC process to see if something actually is changing there?

**Comment by nathanwelch** [comment]
Also @pp-randy would it be possible for us to get in a chat or call with someone technical to get some other info/ideas?

I went ahead and got correlation IDs for the other steps of the process:
 - SetExpressCheckout: `bda44b33add4f`
 - GetExpressCheckoutDetails - `2509ad0d5f1f7`
 - DoExpressCheckoutPayment - `58be5f08be5a5`

Thanks again for your help!

**Comment by pp-randy** [comment]
@nathanwelch from talking to Technical Support they are seeing other contacts on this and are already looking into this issue.

**Comment by shantanut** [comment]
@pp-randy is there an estimate on when this will be resolved?  PayPal is currently broken across our platform.

**Comment by pp-randy** [comment]
@nathanwelch the issue should have been resolved around 11 PM PST last night.  Is everything back up and running? 

@shantanut is everything working for you now?

**Comment by nathanwelch** [comment]
Yes @pp-randy everything is working for us now. Thank you for your help! It seems like the delay in this case was because the engineers working on the fix were in a different timezone from the support staff handling the issues. It's possible that we could have gotten a faster resolution if we had made a support ticket immediately upon seeing the issue (even before we did several hours of our own investigation) because of the timezone difference, so I had a couple of questions about how best to do that in the future:
 
1. **For future issues like this, what's the best escalation or support path to follow?**
2. **When we make support tickets on PayPal Technical Support should we always include correlation IDs to expedite the process?**

**Comment by pp-randy** [comment]
PayPal Technical Support is the best escalation path; especially, with an issue like this when you haven't changed your integration.  Correlation IDs are great to include and will usually speed up the resolution so the engineer can track down your issue quicker.
