### ISSUE TITLE
be lack of PPAutoloader.php in file PPBootStrap.php, which result fatal error

### ISSUE THREAD

**Issue by alibeans** [paypal/merchant-sdk-php#102]
be lack of PPAutoloader.php in file PPBootStrap.php, which result fatal error
path: samples/PPBootStrap.php

**Comment by jaypatel512** [comment]
PPAutoloader file is generated by install.php. this is an alternate way of installing all the dependencies. Our recommended option would be to use composer for any dependency management, which should remove your need for PPAutoloader.php.
