### ISSUE TITLE
Subscription Id not passed 

### ISSUE THREAD

**Issue by kevinn13** [paypal/merchant-sdk-php#104]
there is an issue with subscription id numbers not being passed by get transaction details. They just appear blank this is intermittent and works when it wants to.

**Comment by pp-randy** [comment]
Is this on live or sandbox?  Would you be able to provide a correlation id from one of the responses that had the missing information?

**Comment by kevinn13** [comment]
hi randy 

Thanks for your reply its been like this for over a month it works intermittently on live version sandbox seems ok, but it seems to have got worse the last week. There is a thread on stack about it also http://stackoverflow.com/questions/36167635/paypal-api-nvp-response-for-gettransactiondetails-missing-subscription-id

Here is my response code hope its what you needed if not let me know.
<CorrelationID xmlns="urn:ebay:apis:eBLBaseComponents">8b25b4fb9b83f</CorrelationID

Regards

**Comment by pp-randy** [comment]
For internal tracking PPPLMER-13093

**Comment by pp-randy** [comment]
Additional internal tracking id PPPLCONSMR-32170

**Comment by pp-randy** [comment]
@kevinn13 a fix for this issue should have been pushed yesterday.  Would you be able to review to see if you are getting the expected results?

**Comment by kevinn13** [comment]
Hi Randy 

Can report it all seems to be working ok again.

Thanks for fixing
