### ISSUE TITLE
CreateRecurringPaymentsProfile example not working on production

### ISSUE THREAD

**Issue by GhaziTriki** [paypal/merchant-sdk-php#105]
Hi,

I had some issues to implement CreateRecurringPaymentsProfile in production because the example for sandbox is incomplete, mandatory fileds for the credit card were missing. Do you accept a pull request containing the update?

**Comment by pp-randy** [comment]
Yes please submit a pull request so it can be reviewed.

**Comment by GhaziTriki** [comment]
I just got an answer from PayPal support few days ago. I will provide a pull request as soon as I can.

**Comment by Mahesh-xpertech** [comment]
Hi,
I have problem with CreateRecurringPaymentsProfile with credit card details.I am using sandbox mode.

**Comment by pp-randy** [comment]
@Mahesh-xpertech can you provide the error response? Ensure you provide the correlation id from the response as well please.

**Comment by Mahesh-xpertech** [comment]
Ack :	
Failure
ProfileID :	

PayPal\PayPalAPI\CreateRecurringPaymentsProfileResponseType Object
(
    [CreateRecurringPaymentsProfileResponseDetails] => PayPal\EBLBaseComponents\CreateRecurringPaymentsProfileResponseDetailsType Object
        (
            [ProfileID] => 
            [ProfileStatus] => 
            [TransactionID] => 
            [DCCProcessorResponse] => 
            [DCCReturnCode] => 
        )

    [Timestamp] => 2016-10-26T11:51:06Z
    [Ack] => Failure
    [CorrelationID] => ab1501d7a4074
    [Errors] => Array
        (
            [0] => PayPal\EBLBaseComponents\ErrorType Object
                (
                    [ShortMessage] => DPRP is disabled.
                    [LongMessage] => DPRP is disabled for this merchant.
                    [ErrorCode] => 11586
                    [SeverityCode] => Error
                    [ErrorParameters] => 
                )

        )

    [Version] => 106.0
    [Build] => 000000
)

**Comment by Mahesh-xpertech** [comment]
@pp-randy 
Sir Code that I am using below to create Recurring Payment with credit card info
<?php
use PayPal\CoreComponentTypes\BasicAmountType;
use PayPal\EBLBaseComponents\ActivationDetailsType;
use PayPal\EBLBaseComponents\AddressType;
use PayPal\EBLBaseComponents\BillingPeriodDetailsType;
use PayPal\EBLBaseComponents\CreateRecurringPaymentsProfileRequestDetailsType;
use PayPal\EBLBaseComponents\CreditCardDetailsType;
use PayPal\EBLBaseComponents\RecurringPaymentsProfileDetailsType;
use PayPal\EBLBaseComponents\ScheduleDetailsType;
use PayPal\PayPalAPI\CreateRecurringPaymentsProfileReq;
use PayPal\PayPalAPI\CreateRecurringPaymentsProfileRequestType;
use PayPal\Service\PayPalAPIInterfaceServiceService;
require_once('../PPBootStrap.php');

$currencyCode = "USD";

$AddressType = new AddressType();
$AddressType->Name='test';
$AddressType->Street1='Street1';
$AddressType->Street2='Street2';
$AddressType->CityName='Mohali';
$AddressType->StateOrProvince='dd';
$AddressType->Country='US';
$AddressType->CountryName='India';
$AddressType->Phone='8960915320';
$AddressType->PostalCode='232109';


$RPProfileDetails = new RecurringPaymentsProfileDetailsType();
$RPProfileDetails->SubscriberName='Mahesh';
$RPProfileDetails->BillingStartDate='2016-012-26T00:00:00:000Z';
$RPProfileDetails->SubscriberShippingAddress=$AddressType;


$activationDetails = new ActivationDetailsType();
$activationDetails->InitialAmount = new BasicAmountType('USD','10');
$activationDetails->FailedInitialAmountAction ='ContinueOnFailure';


$paymentBillingPeriod =  new BillingPeriodDetailsType();
$paymentBillingPeriod->BillingFrequency ='1';
$paymentBillingPeriod->BillingPeriod = 'Month';
$paymentBillingPeriod->TotalBillingCycles = '1';
$paymentBillingPeriod->Amount = new BasicAmountType($currencyCode, '10');
$paymentBillingPeriod->ShippingAmount = new BasicAmountType($currencyCode, $_REQUEST['paymentShippingAmount']);
$paymentBillingPeriod->TaxAmount = new BasicAmountType($currencyCode, '0');


$scheduleDetails = new ScheduleDetailsType();
$scheduleDetails->Description='recurring billing';
$scheduleDetails->TrialPeriod='Month';
$scheduleDetails->PaymentPeriod='1';
$scheduleDetails->ActivationDetails = $activationDetails;

$trialBillingFrequency=4;
$trialAmount=10;


	$trialBillingPeriod =  new BillingPeriodDetailsType();
	$trialBillingPeriod->BillingFrequency = 4;
	$trialBillingPeriod->BillingPeriod = 'Day';
	$trialBillingPeriod->TotalBillingCycles = '1';
	$trialBillingPeriod->Amount = new BasicAmountType($currencyCode, '10');
	$trialBillingPeriod->ShippingAmount = new BasicAmountType($currencyCode, '0');
	$trialBillingPeriod->TaxAmount = new BasicAmountType($currencyCode, '0');
	$scheduleDetails->TrialPeriod  = $trialBillingPeriod;


$scheduleDetails->PaymentPeriod = $paymentBillingPeriod;

$maxfailedpayments=0;
$autoBillOutstandingAmount='NoAutoBill';
$scheduleDetails->MaxFailedPayments = $maxfailedpayments;
$scheduleDetails->AutoBillOutstandingAmount = $autoBillOutstandingAmount;


$createRPProfileRequestDetail = new CreateRecurringPaymentsProfileRequestDetailsType();
$creditCard = new CreditCardDetailsType();
	$creditCard->CreditCardNumber ='4311193154103039';
	$creditCard->CreditCardType ='Visa';
	$creditCard->CVV2 = '123';
	$creditCard->ExpMonth =11;
	$creditCard->ExpYear = 2021;
	$createRPProfileRequestDetail->CreditCard = $creditCard;
	
	
	
$createRPProfileRequestDetail->ScheduleDetails = $scheduleDetails;
$createRPProfileRequestDetail->RecurringPaymentsProfileDetails = $RPProfileDetails;
$createRPProfileRequest = new CreateRecurringPaymentsProfileRequestType();
$createRPProfileRequest->CreateRecurringPaymentsProfileRequestDetails = $createRPProfileRequestDetail;

$createRPProfileReq =  new CreateRecurringPaymentsProfileReq();
$createRPProfileReq->CreateRecurringPaymentsProfileRequest = $createRPProfileRequest;




$paypalService = new PayPalAPIInterfaceServiceService(Configuration::getAcctAndConfig());
try {
	/* wrap API method calls on the service object with a try catch */
	$createRPProfileResponse = $paypalService->CreateRecurringPaymentsProfile($createRPProfileReq);
} catch (Exception $ex) {
	include_once("../Error.php");
	exit;
}

if(isset($createRPProfileResponse)) {
	echo "<table>";
	echo "<tr><td>Ack :</td><td><div id='Ack'>$createRPProfileResponse->Ack</div> </td></tr>";
	echo "<tr><td>ProfileID :</td><td><div id='ProfileID'>".$createRPProfileResponse->CreateRecurringPaymentsProfileResponseDetails->ProfileID ."</div> </td></tr>";
	echo "</table>";

	echo "<pre>";
	print_r($createRPProfileResponse);
	echo "</pre>";
}
require_once '../Response.php';

**Comment by pp-randy** [comment]
@Mahesh-xpertech can you try now please?

**Comment by Mahesh-xpertech** [comment]
@pp-randy Now this code return ack is success but transaction is not showing in the sandbox transaction list.

**Comment by Mahesh-xpertech** [comment]
@pp-randy   My response is below from  paypal
Ack :	
Success
ProfileID :	
I-KLNS1LAJF1DG

PayPal\PayPalAPI\CreateRecurringPaymentsProfileResponseType Object
(
    [CreateRecurringPaymentsProfileResponseDetails] => PayPal\EBLBaseComponents\CreateRecurringPaymentsProfileResponseDetailsType Object
        (
            [ProfileID] => I-KLNS1LAJF1DG
            [ProfileStatus] => PendingProfile
            [TransactionID] => 9JX28936K6753834Y
            [DCCProcessorResponse] => 
            [DCCReturnCode] => 
        )

    [Timestamp] => 2016-10-27T05:28:27Z
    [Ack] => Success
    [CorrelationID] => a925ca727841
    [Errors] => 
    [Version] => 106.0
    [Build] => 24616352
)

**Comment by pp-randy** [comment]
I reviewed the transaction and it is associated to your sandbox test account. You would need to log into the sandbox test account at https://www.sandbox.paypal.com.  

I apologize for the confusion to provide more details the the Sandbox Transactions listed here: https://developer.paypal.com/developer/dashboard/sandbox/, these are for the REST API and the SDK for that is here: https://github.com/paypal/PayPal-PHP-SDK  

The above it my assumption of what you might be experiencing.  If this is the case please provide more details around where the transaction is missing and I help further.

**Comment by Mahesh-xpertech** [comment]
@pp-randy  I am using direct payment of sample code but transaction is not showing in the transaction sandbox.. sir Plz help  me with any problem with following Code
<?php
use PayPal\CoreComponentTypes\BasicAmountType;
use PayPal\EBLBaseComponents\AddressType;
use PayPal\EBLBaseComponents\CreditCardDetailsType;
use PayPal\EBLBaseComponents\DoDirectPaymentRequestDetailsType;
use PayPal\EBLBaseComponents\PayerInfoType;
use PayPal\EBLBaseComponents\PaymentDetailsType;
use PayPal\EBLBaseComponents\PersonNameType;
use PayPal\PayPalAPI\DoDirectPaymentReq;
use PayPal\PayPalAPI\DoDirectPaymentRequestType;
use PayPal\Service\PayPalAPIInterfaceServiceService;
/***********************************************************
 DoDirectPayment.php

Submits a credit card transaction to PayPal using a
DoDirectPayment request.

The code collects transaction parameters from the form
displayed by DoDirectPayment.php then constructs and sends
the DoDirectPayment request string to the PayPal server.
The paymentType variable becomes the PAYMENTACTION parameter
of the request string.

After the PayPal server returns the response, the code
displays the API request and response in the browser.
If the response from PayPal was a success, it displays the
response parameters. If the response was an error, it
displays the errors.

Called by DoDirectPayment.html.php.

***********************************************************/
session_start();

require_once('../PPBootStrap.php');
/**
 * Get required parameters from the web form for the request
*/


$firstName = $_POST['firstName'];
$lastName = $_POST['lastName'];

/*
 * shipping adress
*/
$address = new AddressType();
$address->Name = "$firstName $lastName";
$address->Street1 = $_POST['address1'];
$address->Street2 = $_POST['address2'];
$address->CityName = $_POST['city'];
$address->StateOrProvince = $_POST['state'];
$address->PostalCode = $_POST['zip'];
$address->Country = $_POST['country'];
$address->Phone = $_POST['phone'];

$paymentDetails = new PaymentDetailsType();
$paymentDetails->ShipToAddress = $address;

/*
 *  Total cost of the transaction to the buyer. If shipping cost and tax
charges are known, include them in this value. If not, this value
should be the current sub-total of the order.

If the transaction includes one or more one-time purchases, this field must be equal to
the sum of the purchases. Set this field to 0 if the transaction does
not include a one-time purchase such as when you set up a billing
agreement for a recurring payment that is not immediately charged.
When the field is set to 0, purchase-specific fields are ignored.

* `Currency Code` - You must set the currencyID attribute to one of the
3-character currency codes for any of the supported PayPal
currencies.
* `Amount`
*/
$paymentDetails->OrderTotal = new BasicAmountType('USD', $_POST['amount']);
/*
 * 		Your URL for receiving Instant Payment Notification (IPN) about this transaction. If you do not specify this value in the request, the notification URL from your Merchant Profile is used, if one exists.

*/
if(isset($_REQUEST['notifyURL']))
{
	$paymentDetails->NotifyURL = $_REQUEST['notifyURL'];
}

$personName = new PersonNameType();
$personName->FirstName = $firstName;
$personName->LastName = $lastName;

//information about the payer
$payer = new PayerInfoType();
$payer->PayerName = $personName;
$payer->Address = $address;
$payer->PayerCountry = $_POST['country'];

$cardDetails = new CreditCardDetailsType();
$cardDetails->CreditCardNumber = $_POST['creditCardNumber'];

/*
 *
Type of credit card. For UK, only Maestro, MasterCard, Discover, and
Visa are allowable. For Canada, only MasterCard and Visa are
allowable and Interac debit cards are not supported. It is one of the
following values:

* Visa
* MasterCard
* Discover
* Amex
* Solo
* Switch
* Maestro: See note.
`Note:
If the credit card type is Maestro, you must set currencyId to GBP.
In addition, you must specify either StartMonth and StartYear or
IssueNumber.`
*/
$cardDetails->CreditCardType = $_POST['creditCardType'];
$cardDetails->ExpMonth = $_POST['expDateMonth'];
$cardDetails->ExpYear = $_POST['expDateYear'];
$cardDetails->CVV2 = $_POST['cvv2Number'];
$cardDetails->CardOwner = $payer;

$ddReqDetails = new DoDirectPaymentRequestDetailsType();
$ddReqDetails->CreditCard = $cardDetails;
$ddReqDetails->PaymentDetails = $paymentDetails;
$ddReqDetails->PaymentAction = $_REQUEST['paymentType'];

$doDirectPaymentReq = new DoDirectPaymentReq();
$doDirectPaymentReq->DoDirectPaymentRequest = new DoDirectPaymentRequestType($ddReqDetails);

/*
 * 		 ## Creating service wrapper object
Creating service wrapper object to make API call and loading
Configuration::getAcctAndConfig() returns array that contains credential and config parameters
*/
$paypalService = new PayPalAPIInterfaceServiceService(Configuration::getAcctAndConfig());
try {
	/* wrap API method calls on the service object with a try catch */
	$doDirectPaymentResponse = $paypalService->DoDirectPayment($doDirectPaymentReq);
} catch (Exception $ex) {
	include_once("../Error.php");
	exit;
}
if(isset($doDirectPaymentResponse)) {
	echo "<table>";
	echo "<tr><td>Ack :</td><td><div id='Ack'>$doDirectPaymentResponse->Ack</div> </td></tr>";
	echo "<tr><td>TransactionID :</td><td><div id='TransactionID'>$doDirectPaymentResponse->TransactionID</div> </td></tr>";
	echo "</table>";
	echo "<pre>";
	print_r($doDirectPaymentResponse);
	echo "</pre>";
}
require_once '../Response.php';
?>

**Comment by pp-randy** [comment]
Which URL are you not seeing the transaction on?  I can see them on your sandbox account.

**Comment by Mahesh-xpertech** [comment]
@pp-randy 
using below URL for seeing transaction but it is not listed in...
https://developer.paypal.com/developer/dashboard/sandbox/
Merchant Account is credited every time but buyer account is not debited(decreased) any single time

**Comment by Mahesh-xpertech** [comment]
@pp-randy 
Now the current transaction id is 93C76230BE3561808 and not listed in the transaction account.

**Comment by pp-randy** [comment]
Your transactions will not show in that URL because they are not created with the REST API.  Please review this previous comment.

> You would need to log into the sandbox test account at https://www.sandbox.paypal.com.
 
From here: https://github.com/paypal/merchant-sdk-php/issues/105#issuecomment-256641832

**Comment by pp-randy** [comment]
If you do not know the password for your merchant sandbox account to log into https://www.sandbox.paypal.com you can change it here: https://developer.paypal.com/developer/accounts/ and then click the Profile link for that account.
