### ISSUE TITLE
Namespace conflict with other PHP SDK's

### ISSUE THREAD

**Issue by vbresults** [paypal/merchant-sdk-php#112]
Please change the root namespace to `PayPal\Merchant` (a la ZF) so it does not conflict with other SDK's, otherwise we can't use these two alongside each other without headaches...

See #97.  Refactoring the `PayPalAPI` folder into `API` would be nice too (not necessary)... can submit PR for one or both suggestions if necessary.

Before: `PayPal\PayPalAPI\AddressVerifyReq` After: `PayPal\Merchant\API\AddressVerifyReq`

Ping @jaypatel512

**Comment by jaypatel512** [comment]
Hey @vbresults !

The issue is with the existing integrations. This will cause the previous integrations to fail, unless we make a major release for this. We would be more than happy to accept a PR for this.

thank you again @vbresults for helping us with this. We may be able to make the naming convention consistent across all classic SDKs too. But that could be for later.

**Comment by vbresults** [comment]
@jaypatel512 Implementing this and deploying it can be considered two separate tasks -- so if we make a new branch, call it PSR-4, and make it available, it won't disturb `2.x` and `master`.

In the meantime, it can get battle-tested as there are surely lots of people out there looking for this, and when the time is right, then we can discuss a full-out release.  Thoughts?

**Comment by jaypatel512** [comment]
I completely agree. I will discuss with the team tomorrow, and see what their thoughts are on prioritizing this, and get it released soon. Let the PRs begin 🎆

**Comment by vbresults** [comment]
@jaypatel512 Submitted PR's for this repo (#113) as well as the REST API and Core repos, and am using them simultaneously with success (:

**Comment by jaypatel512** [comment]
You should not have any conflicts with the [PayPal-PHP-SDK for REST](https://github.com/paypal/PayPal-PHP-SDK) at all. I don't think we need to update the namespaces for REST PHP SDK.

**Comment by vbresults** [comment]
@jaypatel512 Doesn't make sense to mix the REST folders with full-blown sdk's (i.e. Merchant SDK) -- it would add confusion instead of making things more uniform, hence the REST namespace update.

**Comment by jaypatel512** [comment]
PRs related to this issue: 

- https://github.com/paypal/PayPal-PHP-SDK/pull/614
- https://github.com/paypal/sdk-core-php/pull/82
- https://github.com/paypal/merchant-sdk-php/pull/113

**Comment by jaypatel512** [comment]
Released [Button Manager 4.0.0](https://github.com/paypal/buttonmanager-sdk-php/releases/tag/v4.0.0). Please read the migration guide to use it with merchant SDK.
