### ISSUE TITLE
DoReferenceTransaction bug

### ISSUE THREAD

**Issue by KelseySheely** [paypal/merchant-sdk-php#114]
We are getting a 500 any time we try to run a DoReferenceTransaction call to the PayPal sandbox.  I have a ticket in with PayPal but they have not yet found anything and are frankly not being very responsive.  I've tried using both the Billing Agreement ID and the Original Payment Transaction ID as the ReferenceId with the same results.  Here is a log of the error:

`PayPal\Exception\PPConnectionException::__set_state(array(
   'url' => 'https://api-3t.sandbox.paypal.com/2.0',
   'data' => '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:ed="urn:ebay:apis:EnhancedDataTypes" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:ns="urn:ebay:api:PayPalAPI"><SOAP-ENV:Header><Security xmlns="http://schemas.xmlsoap.org/ws/2002/12/secext" xsi:type="wsse:SecurityType"></Security><RequesterCredentials xmlns="urn:ebay:api:PayPalAPI" xsi:type="ebl:CustomSecurityHeaderType"><Credentials xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:UserIdPasswordType"><Username xsi:type="xs:string">kelsey_api1.theapiguys.com</Username><Password xsi:type="xs:string">2T9GKJXFEMXYHU4Z</Password><Signature xsi:type="xs:string">AjGzl3P4pvUkxzvvPS11Za5QW2qgAtN076I8yWDEWEt4e-6d-8YvDfWU</Signature></Credentials></RequesterCredentials></SOAP-ENV:Header><SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" id="_0"><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>Method \'ebl:DoReferenceTransactionRequestDetails\' not implemented</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>',
   'message' => 'Got Http response code 500 when accessing https://api-3t.sandbox.paypal.com/2.0.',
   'string' => '',
   'code' => 0
))`

And here is the full request:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="urn:ebay:api:PayPalAPI" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:ed="urn:ebay:apis:EnhancedDataTypes" ><soapenv:Header><ns:RequesterCredentials><ebl:Credentials><ebl:Username>kelsey_api1.theapiguys.com</ebl:Username><ebl:Password>2T9GKJXFEMXYHU4Z</ebl:Password><ebl:Signature>AjGzl3P4pvUkxzvvPS11Za5QW2qgAtN076I8yWDEWEt4e-6d-8YvDfWU</ebl:Signature></ebl:Credentials></ns:RequesterCredentials></soapenv:Header><soapenv:Body><ebl:DoReferenceTransactionRequestDetails><ebl:DoReferenceTransactionRequestDetails><ebl:ReferenceID>B-3LA09144AE004763U</ebl:ReferenceID><ebl:PaymentAction>Sale</ebl:PaymentAction><ebl:PaymentDetails><ebl:OrderTotal currencyID="USD">597</ebl:OrderTotal><ebl:ButtonSource>PayPal_SDK</ebl:ButtonSource><ebl:NotifyURL>http://samovens/paypal_return?type=ipn</ebl:NotifyURL></ebl:PaymentDetails></ebl:DoReferenceTransactionRequestDetails></ebl:DoReferenceTransactionRequestDetails></soapenv:Body></soapenv:Envelope>`

**Comment by pp-randy** [comment]
It looks like the Method name being picked up as DoReferenceTransactionRequestDetails instead of DoReferenceTransaction.

Are you setting the request object like this sample? https://github.com/paypal/merchant-sdk-php/blob/master/samples/BillingAgreements/DoReferenceTransaction.php#L119

**Comment by KelseySheely** [comment]
Thanks Randy,

I did in fact have the last method name set to DoReferenceTransactionRequestType rather than DoReferenceTransactionReq.  Thanks, I was banging my head against the wall on that one.  However, now that I fixed that I am getting a version error:

```
PayPal\PayPalAPI\DoReferenceTransactionResponseType::__set_state(array(
   'DoReferenceTransactionResponseDetails' => NULL,
   'FMFDetails' => NULL,
   'Timestamp' => '2016-08-01T23:04:00Z',
   'Ack' => 'Failure',
   'CorrelationID' => '5d75a5da3fa3a',
   'Errors' => 
  array (
    0 => 
    PayPal\EBLBaseComponents\ErrorType::__set_state(array(
       'ShortMessage' => 'Version error',
       'LongMessage' => 'Version is not supported',
       'ErrorCode' => '10006',
       'SeverityCode' => 'Error',
       'ErrorParameters' => NULL,
    )),
  ),
   'Version' => '0.000000',
   'Build' => '22386173',
))
```
Any additional thoughts about that?

**Comment by KelseySheely** [comment]
I got it figured out.  Thanks again for the help.

My problem was that I was trying to pass the DoReferenceTransactionRequestType object to the constructor of the DoReferenceTransactionReq object, but it looks like it does not accept that as a parameter.
