### ISSUE TITLE
Using newer API Version ?

### ISSUE THREAD

**Issue by gswebspace** [paypal/merchant-sdk-php#116]
Hi,

Going through the code at [/lib/PayPal/Service/PayPalAPIInterfaceServiceService.php](https://github.com/paypal/merchant-sdk-php/blob/master/lib/PayPal/Service/PayPalAPIInterfaceServiceService.php#L117) I see that the SDK uses the $SERVICE_VERSION as "106.0" but reviewing the [API Version History](https://developer.paypal.com/docs/classic/release-notes/#ec) I see that Version 106 was released back in 2013. With the latest being Version 204 released in March 2016.

Q1 - Is it still recommended to use that version(106) for a fresh integration (for a simple Express Checkout) ?

Q2 - How can I change this version ? (Should I just hard-code it or is there any method/config
 available for it ?)

Let me know, Thanks !

**Comment by rayfly** [comment]
I also have this problem.
Could I use version 104.0 ?
What is the different ?
Would it make error because I see the version is 204 now ?
Thank you ~

**Comment by pp-randy** [comment]
@gswebspace for a fresh integration you should look at https://github.com/paypal/PayPal-PHP-SDK, and use PayPal as the payment method, which is the same as doing an Express Checkout with this SDK.

**Comment by pp-randy** [comment]
@rayfly you can use 104.0.  PayPal tries to introduce changes with new API versions and not break existing API versions, so 204 has some fields and or methods not available on 104.

**Comment by pp-randy** [comment]
After discussing with the development team, using 204 with the SDK should not cause an issue though.

**Comment by pp-randy** [comment]
@gswebspace you would have to change it in the code.
