### ISSUE TITLE
Installation Without Composer

### ISSUE THREAD

**Issue by OptrixAU** [paypal/merchant-sdk-php#118]
My hosting provider - one of Australias largest - doesn't support either SSH access or Composer via CPanel, which means there is no way to install the package.

The package **does** include what appears to be an installer of some kind, but it's contained in the _samples_ rather than the base library, and there is no information about how its used (and some searching would indicate that it's deprecated).

I'd like to either have instructions for manual installation, or some alternative to allow installation when composer is unavailable.

**Comment by jaypatel512** [comment]
You can run `composer` in your desktop/laptop, and upload the final build via FTP. This should allow you to upload all the files inside `vendor` directory auto generated to hold all these composer based files.

**Comment by Prento956** [comment]
@jaypatel512 Im kinda new this whole app creation, taught myself php and decided to learn android/ios app creation. Question how do i compile this app, and what do i need https://github.com/paypal/PayPal-Android-SDK

**Comment by krwags** [comment]
When I run composer on this merchantSDK, it's doesn't place the core files and the merchant sdk in the same place and the autoloader can't find the core.  

Why is this so difficult to install?

**Comment by xiaoleih41** [comment]
Is there a specific reason you want to use this SDK? As we are deprecating NVP/SOAP API. I would strongly recommend you to use our [REST SDK](https://github.com/paypal/PayPal-PHP-SDK) instead. Please follow the instruction and you should be able to download the SDK with all required files.
