### ISSUE TITLE
PreapprovalDetailsResponse Object returns empty

### ISSUE THREAD

**Issue by sachy123** [paypal/merchant-sdk-php#119]
So I am now testing if the preapproval response can give me actual status for the Preapproval Key.
I fed the PreapprovalDetailsRequest Object with the appropriate preApprovalKey.
But in response, I am getting everything empty. as you can see below

Is this a bug in PreapprovalDetailsRequest.php?

```
`PreapprovalDetailsRequest Object ( [requestEnvelope] => RequestEnvelope Object ( [detailLevel] => [errorLanguage] => en_US ) [preapprovalKey] => PA-94C106ddd1231931052V [getBillingAddress] => )
`
```
-----------------------
`
PreapprovalDetailsResponse Object ( [responseEnvelope] => [approved] => [cancelUrl] => [curPayments] => [curPaymentsAmount] => [curPeriodAttempts] => [curPeriodEndingDate] => [currencyCode] => [dateOfMonth] => [dayOfWeek] => [endingDate] => [maxAmountPerPayment] => [maxNumberOfPayments] => [maxNumberOfPaymentsPerPeriod] => [maxTotalAmountOfAllPayments] => [paymentPeriod] => [pinType] => [returnUrl] => [senderEmail] => [memo] => [startingDate] => [status] => [ipnNotificationUrl] => [addressList] => [feesPayer] => [displayMaxTotalAmount] => [sender] => [agreementType] => [error] => ) `

**Comment by pp-randy** [comment]
The preapproval key does not validate for my lookup. Do you have the correlation ID of the request that generated the pre approval key?  

For the failed lookup are you able to log the SOAP response?

**Comment by pp-randy** [comment]
Are you using this SDK https://github.com/paypal/adaptivepayments-sdk-php?

**Comment by sachy123** [comment]
No 
The first step is that I retrieve the preapproval key. Then I use that preapproval key for getting pre approval from the sender.
Once that is done I want to see the details e.g. if the pre approval was canceled or accepted.
So I use the PreapprovalDetails.php

**Comment by sachy123** [comment]
Yes I am using that sdk

**Comment by pp-randy** [comment]
The preapproval key is too long, it should be only 20 characters which is why I couldn't look it up.  I need more information about how you are generating the actual preapproval key, so the request you are sending to /AdaptivePayments/Preapproval endpoint.

**Comment by sachy123** [comment]
You can't get other details because thats the application configuration. However preapproval I'd is exact. 
I am not sure why response object gives me an empty results
I expect it to fetch all the information for that pre approval

**Comment by pp-randy** [comment]
Is this happening in production?  If so, can you create a ticket with PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask

If this is happening in sandbox can you give anything more than [preapprovalKey] => PA-94C106ddd1231931052V ?  Your sandbox account or any correlation_id value from an API response?

**Comment by sachy123** [comment]
Ah no its sandbox .

**Comment by sachy123** [comment]
What is a correlation_id ?
How can I get it ?

**Comment by pp-randy** [comment]
It should be a value in the API response.  The wiki has some details about turning on logging https://github.com/paypal/sdk-core-php/wiki/Configuring-the-SDK#logging

**Comment by sachy123** [comment]
Ok I will try to get it. Hope it helps. Although it's not mentioned in the samples anywhere. It says I have to feed Pre Approval ID with correct configuration and it will get details of preapproval

**Comment by sachy123** [comment]
it didnt work
its showing me again empty object and I followed exactly the same process as described by Paypal in the link below
**Step 3: Retrieve Data about the Preapproval (Optional)**
[See Step 3 ](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicPreapproval-curl-etc/)
please note the input parameters 
Input Parameters
----------------
_preapprovalKey=PA-5PU68213WY5961234    #Value of the preapproval key, received in the Preapproval call above
&requestEnvelope.errorLanguage=en_US_

this is exactly the similar format of the preapproval key as I have used in my example , and funnything is that even if I feed anything, it doesnot even show me an error, its returning me the same empty object as seen in my first post.

**Comment by sachy123** [comment]
Can someone give me a WORKING example of Getting PreapprovalDetailsRequest

**Comment by pp-randy** [comment]
The Sample in the Adaptive Repo is working for me:
https://github.com/paypal/adaptivepayments-sdk-php/blob/master/samples/PreapprovalDetails.php
Which Posts to 
https://github.com/paypal/adaptivepayments-sdk-php/blob/master/samples/PreapprovalDetailsReceipt.php

**Comment by sachy123** [comment]
Yes but can you please paste a sample of the response object
which is output of the following code?

```
$response = $service->PreapprovalDetails($preapprovalDetailsRequest);
print_r($response )
```

**Comment by sachy123** [comment]
@pp_randy can you please paste the output of the response below.
Thanks
Sachy

**Comment by pp-randy** [comment]
I will capture a response for you and update shortly. 

The following guide does not have the PreapprovalDetails API call but may be beneficial to you for the others https://devtools-paypal.com/guide/ap_preapprove_payment/php?interactive=ON&env=sandbox

**Comment by pp-randy** [comment]
This is the preapproval provided in the samples but it works for a newer one as well. 
```
PayPal\Types\AP\PreapprovalDetailsResponse Object
(
    [responseEnvelope] => PayPal\Types\Common\ResponseEnvelope Object
        (
            [timestamp] => 2016-10-03T07:03:34.994-07:00
            [ack] => Success
            [correlationId] => XXXXXXX
            [build] => 25712129
        )

    [approved] => false
    [cancelUrl] => http://localhost/dev/adaptivepayments-php-sdk/Preapproval.php
    [curPayments] => 0
    [curPaymentsAmount] => 0.00
    [curPeriodAttempts] => 0
    [curPeriodEndingDate] => 
    [currencyCode] => USD
    [dateOfMonth] => 0
    [dayOfWeek] => NO_DAY_SPECIFIED
    [endingDate] => 2012-02-23T23:59:28.000-08:00
    [maxAmountPerPayment] => 
    [maxNumberOfPayments] => 10
    [maxNumberOfPaymentsPerPeriod] => 
    [maxTotalAmountOfAllPayments] => 50.00
    [paymentPeriod] => NO_PERIOD_SPECIFIED
    [pinType] => NOT_REQUIRED
    [returnUrl] => http://localhost/dev/adaptivepayments-php-sdk/Preapproval.php
    [senderEmail] => 
    [memo] => 
    [startingDate] => 2012-02-13T00:00:28.000-08:00
    [status] => CANCELED
    [ipnNotificationUrl] => 
    [addressList] => 
    [feesPayer] => SENDER
    [displayMaxTotalAmount] => false
    [sender] => 
    [agreementType] => 
    [error] => 
)
```

**Comment by sachy123** [comment]
ThIs is strange because I am trying to capture the response object .. but it's just  empty !!! I don't know what is wrong.

**Comment by pp-randy** [comment]
Your other API calls are working correctly?

**Comment by sachy123** [comment]
Yep . I get the Pre approval via api calls. I store the preapprovalkey  and use that preapprovalkey to create a url to redirect the user to aquire a preapproval. 
But now i am just stuck to get the status of preapproval to know from an application if the user accepted or cancelled

**Comment by pp-randy** [comment]
Can you see if for some reason an exception is being thrown?
https://github.com/paypal/adaptivepayments-sdk-php/blob/master/samples/PreapprovalDetailsReceipt.php#L28-L35

**Comment by sachy123** [comment]
I checked but there were no exceptions. In anycase I will check it again.  And try to post my code and the structure

**Comment by sachy123** [comment]
```
public function actionPaypalDetails()
{

  if (isset($_GET['PPcode']))
  {
      /*
 * Use the PreapprovalDetails API operation to obtain information about an agreement between you and a sender for making payments on the sender’s behalf. 
 */
/*
 * The PreapprovalDetailsRequest message specifies the key of the preapproval agreement whose details you want to obtain.
 */
/*
 * (Required) Information common to each API operation, such as the language in which an error message is returned.
 */
$requestEnvelope = new RequestEnvelope("en_US");
/*
 * (Required) A preapproval key that identifies the preapproval for which you want to retrieve details. The preapproval key is returned in the PreapprovalResponse message.
 */
$preapprovalDetailsRequest = new PreapprovalDetailsRequest();
$preapprovalDetailsRequest->preapprovalKey = "PA-94C1061231931052V";
/*
 *   ## Creating service wrapper object
Creating service wrapper object to make API call and loading
Configuration::getAcctAndConfig() returns array that contains credential and config parameters
 */
$service = new AdaptivePaymentsService(Yii::app()->params['PaypalConfig']);
try {
  // print_r($service);
  // /* wrap API method calls on the service object with a try catch */
  // print_r("<BR>");
  // print_r("<HR>");
  // print_r($preapprovalDetailsRequest);
  // print_r("<BR>");
  // print_r("<HR>");
  $response = $service->PreapprovalDetails($preapprovalDetailsRequest);
  // $ack = strtoupper($response->responseEnvelope->ack);
  print_r($response);
  // exit();
  // print_r($ack);
  
} catch(Exception $ex) {
  print_r($ex);
  // require_once 'Common/Error.php';
  exit(); 
}
exit();

 }

 $this->render('PaypalDetails');
  
}
```

**Comment by sachy123** [comment]
```
'acct1.UserName' => 'sachin.mandalia-facilitator_api1.arzeno-it.com',
'acct1.Password' => 'D72EH2WXA5QA3RNU',
'acct1.Signature' => 'AFcWxV21C7fd0v3bYYYRCpSSRl31Av6jN.P79jX1RToXBlRjLsob.IVY',
"acct1.AppId" => "APP-80W284485P519543T"
```

**Comment by sachy123** [comment]
please let me know if I am wrong anywhere? or if you get the details using the configuration above?

**Comment by sachy123** [comment]
`$preapprovalDetailsRequest->preapprovalKey = "PA-94C1061231931052V";`

**Comment by sachy123** [comment]
I am using Yii MVC architecture

**Comment by sachy123** [comment]
So finally I got something but there is an error as below
`
responseEnvelope.timestamp=2016-10-07T06%3A14%3A34.045-07%3A00&responseEnvelope.ack=Failure&responseEnvelope.correlationId=a10247cdec54a&responseEnvelope.build=25712129&error(0).errorId=580022&error(0).domain=PLATFORM&error(0).subdomain=Application&error(0).severity=Error&error(0).category=Application&error(0).message=Invalid+request+parameter%3A+requestEnvelope+cannot+be+null&error(0).parameter(0)=requestEnvelope&error(0).parameter(1)=null`

**Comment by pp-randy** [comment]
The error indicates the requestEnvelope is incorrect.  What does your code look like for creating the request?  It should look similar to this 
https://github.com/paypal/adaptivepayments-sdk-php/blob/master/samples/PaymentDetailsReceipt.php#L17-L23

**Comment by sachy123** [comment]
I solved it!!!
Thanks PP_Randy for your patience
