### ISSUE TITLE
API version is to low

### ISSUE THREAD

**Issue by brilsergei** [paypal/merchant-sdk-php#125]
Hi
Current API version is 204, but SDK supports only 106, released on 2013-Aug-20. I need to use SoftDescriptor field added in version 115 for direct payments. Is there a way to fix it?

is the library maintained by paypal? if so, it looks strange that api updates takes so much time.

**Comment by gswebspace** [comment]
Referencing a similar issue #116 I had. Maybe it can help. 

(Do consider the input from the team regarding the 'SoftDescriptor' field, I am not sure about that)

**Comment by jaypatel512** [comment]
Hey @brilsergei @gswebspace !

You are correct. We are still maintaining these repositories, however, these SDKs are under maintenance only, and are rarely updated based on security updates. From the looks of it, the field you are trying to use seems to be important, we will try and prioritize this work, and update the SDKs soon. Will update this issue once updated. 

Thanks.

**Comment by jaypatel512** [comment]
Recently made a release, that upated the stubs at https://github.com/paypal/merchant-sdk-php/releases/tag/v3.11.0
