### ISSUE TITLE
Fatal error: Class 'PayPalAPIInterfaceServiceService' not found

### ISSUE THREAD

**Issue by mohsinabba** [paypal/merchant-sdk-php#127]
Its a nightmare to use this SDK. I have already run install.php without composer and all 3 folders 
a. paypal-merchant-sdk-php-XXXXXXX
b. paypal-permissions-sdk-php-XXXXXXX
c. paypal-sdk-core-php-XXXXXX
are there just for some reasons the "PayPalAPIInterfaceServiceService" not loaded up however i can see the class in:
root >
     vendor > paypal > paypal-merchant-sdk-php-XXXXXX >lib > PayPal > Service > PayPalAPIInterfaceServiceService.php exist

When i print the class name spl function passes to loadClass i see the following on screen:

PayPal\CoreComponentTypes\BasicAmountType

PayPal\Core\PPXmlMessage

PayPal\EBLBaseComponents\AddressType

PayPal\EBLBaseComponents\PaymentDetailsType

PayPal\EBLBaseComponents\PaymentDetailsItemType

PayPal\EBLBaseComponents\SetExpressCheckoutRequestDetailsType

PayPal\PayPalAPI\SetExpressCheckoutRequestType

PayPal\EBLBaseComponents\AbstractRequestType

PayPal\PayPalAPI\SetExpressCheckoutReq

PayPalAPIInterfaceServiceService

you see the PayPalAPIInterfaceServiceService missing PayPal\Service even though it has been mentioned in the file:
use PayPal\CoreComponentTypes\BasicAmountType;
use PayPal\EBLBaseComponents\AddressType;
use PayPal\EBLBaseComponents\BillingAgreementDetailsType;
use PayPal\EBLBaseComponents\PaymentDetailsItemType;
use PayPal\EBLBaseComponents\PaymentDetailsType;
use PayPal\EBLBaseComponents\SetExpressCheckoutRequestDetailsType;
use PayPal\PayPalAPI\SetExpressCheckoutReq;
use PayPal\PayPalAPI\SetExpressCheckoutRequestType;
use PayPal\Service\PayPalAPIInterfaceServiceService;
I don't have time to waste on debugging, can you point to the right direction?

**Comment by mohsinabba** [comment]
Nevermind, my bad.. i missed it use PayPal\Service\PayPalAPIInterfaceServiceService; on the page i am creating the class instance on.

**Comment by pp-randy** [comment]
Thank you for following up @mohsinabba.
