### ISSUE TITLE
Coupon/Discount in Express Checkout

### ISSUE THREAD

**Issue by mohsinabba** [paypal/merchant-sdk-php#128]
I don't see any way to declare coupon or discount value for express checkout other than adding a item line with negative value or i missed something?

**Comment by pp-randy** [comment]
Negative Line items are the way to do it
https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/
![image](https://cloud.githubusercontent.com/assets/6819909/22831755/21402972-ef71-11e6-8509-65289dfddf6e.png)

For a new integration using Express Checkout, I would advise using https://github.com/paypal/PayPal-PHP-SDK and the PayPal payments option.
