### ISSUE TITLE
I have find a Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [paypal/merchant-sdk-php#129]
Hello:
   I have find a Reflected XSS vulnerability in this sdk.

   The vulnerability exists due to insufficient filtration of user-supplied data in “token” HTTP GET parameter that will be passed to “merchant-sdk-php\samples\AccountAuthentication\GetAuthDetails.html.php”. The infected source code is line 7,  there is  no protection on _GET[‘token’]; if _GET[‘token’] contains evil js code, line 21 will trigger untrusted code to be excuted on the browser side.

![image](https://cloud.githubusercontent.com/assets/1484292/22834995/2046b58c-eff2-11e6-9c13-b5c23ba47947.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
"http://localhost/php-pro/merchant-sdk-php-master/AccountAuthentication/GetAuthDetails.html.php?token=><script>alert(1);</script>"

The follow scrrenshot is the result to click the upper url ( win7 spq x64 + firefox 51.0.1 32bit ):
![image](https://cloud.githubusercontent.com/assets/1484292/22835581/384dc628-eff4-11e6-9f95-4c3a560d0372.png)

 **Discoverer: Haojun Hou, DongWang in ADLab of Venustech**

**Comment by pp-randy** [comment]
Thank you for submitting the issue. Would you be interested in submitting a pull request to help resolve this?  If not, it is ok I will review further.

**Comment by jgj212** [comment]
@pp-randy  i am sorry, i am not skilled at bug fixing.  You can encode the user input from the browser side,  because it is not trusted .

**Comment by pp-randy** [comment]
Adding internal tracking: BTDXCLTS-283
