### ISSUE TITLE
Reflected XSS vulnerability found in the merchant SDK.

### ISSUE THREAD

**Issue by DrHazemAli** [paypal/merchant-sdk-php#134]
### Issue description

There's a Reflected XSS vulnerability in the merchant SDK.
The vulnerability exists due to insufficient filtration of user-supplied data in token.
See Below!

### Proof 

![alt tag](https://s18.postimg.org/ndvrfsjt5/paypal.png)

### Fixes
i've submitted a pull-request which includes fixes.

**Comment by pp-randy** [comment]
This is already being tracked here: https://github.com/paypal/merchant-sdk-php/issues/129
