### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by FexileTV** [paypal/merchant-sdk-php#135]
Doesn't PayPal require you to use some keys?

REST API Apps?

Like Secret or something? Or is that what you mean with Password?

**Comment by pp-randy** [comment]
Sorry for the delay @FexileTV.  I think you are wanting the REST API SDK here: https://github.com/paypal/PayPal-PHP-SDK

Also this should be helpful: 
https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call

Sorry again for the delay.  I will close this issue, but if you need anything else let me know.
