### ISSUE TITLE
Broken XML produced for SetExpressCheckout request when using "cpp*" fields

### ISSUE THREAD

**Issue by piazzon-f** [paypal/merchant-sdk-php#136]
### General information

* SDK/Library version: 3.11.0
* Environment: tested only in Sandbox

### Issue description
PSR compliant linting in commit c9a15d773fcbca7f052b7524c9103889142fa552 modified the ```@name``` annotation for "cpp*" fields in [SetExpressCheckoutRequestDetailsType.php](https://github.com/paypal/merchant-sdk-php/blob/master/lib/PayPal/EBLBaseComponents/SetExpressCheckoutRequestDetailsType.php#L259) introducing a space character that has broken the resulting XML request output when one of the cpp* fields is specified.

**Comment by gerardnll** [comment]
Bug also present in 3.10.0, rolled back to 3.9.1.

**Comment by jaypatel512** [comment]
Hey @piazzon-f @gerardnll ! I have created a PR fixing this. Can you please help me review it, and make sure I have not missed anything else.
