### ISSUE TITLE
Unable to use the Button Manager API calls

### ISSUE THREAD

**Issue by speller** [paypal/merchant-sdk-php#137]
The package contain classes `BMCreateButtonReq` and so on, but the `PayPalAPIInterfaceServiceService` do not contain methods fort them. The `PayPalAPIInterfaceServiceService` class in the ButtonManagerSDK package contain them, but it is impossible to use these packages simultaneously in single app because of duplicate class names. Please move the Button Manager functionality to the MerchantSDK.

Also, I can't add this functionality by myself by extending existing PayPalAPIInterfaceServiceService class because many of its important fields and methods are marked as private and are inaccessible from inherited classes.

**Comment by jaypatel512** [comment]
Released [Button Manager 4.0.0](https://github.com/paypal/buttonmanager-sdk-php/releases/tag/v4.0.0). Please read the migration guide to use it with merchant SDK.

**Comment by sellegabuya** [comment]
Hi @jaypatel512 would you mind to view this #143 ? thanks
