### ISSUE TITLE
PPAutoloader.php

### ISSUE THREAD

**Issue by GallantGentleman** [paypal/merchant-sdk-php#138]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Where is "PPAutoloader.php" file ?

**Comment by pp-randy** [comment]
It gets generated by the install.php in samples. I found a similar issue here: https://github.com/paypal/adaptivepayments-sdk-php/issues/21#issuecomment-171197201

For a newer integration I would recommend https://github.com/paypal/PayPal-PHP-SDK if the PayPal REST API fits your needs.
