### ISSUE TITLE
Paypal Vaulted Credit Cards

### ISSUE THREAD

**Issue by sellegabuya** [paypal/merchant-sdk-php#143]
Hi guys,
I would like to ask if this sdk also supports Vaulted Credit Cards.
If so, what would be the process when it comes to recurring payments?

Thanks

**Comment by pp-randy** [comment]
Hi @sellegabuya,

Currently recurring payments and the vaulted credit cards are not supported.  We are tracking a feature for that here https://github.com/paypal/PayPal-REST-API-issues/issues/3.

The SDK that supports vault with the PayPal REST API is the [PayPal-PHP-SDK](https://github.com/paypal/PayPal-PHP-SDK), if you are looking for PHP.
