### ISSUE TITLE
Order total not displayed on Paypal Landing Page

### ISSUE THREAD

**Issue by godzou** [paypal/merchant-sdk-php#144]
### General information

SDK/Library version : SDK 3.9.1
Environment : Sandbox and Production

### Issue description

Hi, 
I got a problem with information displayed on the Paypal page, the SDK works perfectly (I can make an order and pay with the sandbox for example) but the total of the order does not display on the Paypal landing page and I don't understand why. I tried some different parameters but there is nothing to do the total is always missing, even with production keys (today I use the old classic NVP API and it works).

I only send the total of the order ("OrderTotal") because I don't want to send all the total items, shipping, handling etc...

Furthermore I have a mysterious sentence on the confirmation page : "Vous pourrez vérifiez votre commande avant d'effectuer votre achat" (You'll can check your order before to make your purchase), but the continue button is already the final step to complete the order before redirect, so the sentence is wrong, how can I remove it ?

Thanks for help.

**Comment by xiaoleih41** [comment]
In your situation, you will need add `&useraction=commit` to the end of URL when you redirect the buyer to the PayPal website. This will solve both issues.

**Comment by godzou** [comment]
It works ! Thanks a lot for your fast reply.
