### ISSUE TITLE
DoReferenceTransaction - Agreement Id not valid

### ISSUE THREAD

**Issue by saber666** [paypal/merchant-sdk-php#145]
Hi - I created an agreement using Paypal-API. The agreement is processing recurring payments every two weeks and I have verified using the sandbox dashboard.  Due to the inability to change the amount of the billing agreement every two weeks I'd like to use the DoReferenceTransaction to charge the difference. I'm able to retrieve the agreement details using GetRecurringPaymentsProfileDetails in the sample but unable to process a DoReferenceTransaction. This is the message I receive: Billing Agreement Id or transaction Id is not valid. I passed the same id I used for GetRecurringPaymentsProfileDetails which seems to be the profile id. I also tried passing a transaction id from one of the recurring payments but get the same error. I'm unable to find any other id that I can pass. How can I find the agreement id or fix this error?

**Comment by xiaoleih41** [comment]
Recurring payment billing agreement ID cannot be used for reference transaction payment. If your billing agreement involves various amount, please use reference transaction only for your billing agreement. Please follow the instructions on [this site](https://developer.paypal.com/docs/classic/express-checkout/ec_set_up_reference_transactions/).  to build your billing agreement by using reference transaction only.

**Comment by saber666** [comment]
Thanks @xiaoleih41!
