### ISSUE TITLE
How impliment ACH in php

### ISSUE THREAD

**Issue by axay-ordex** [paypal/merchant-sdk-php#146]
Hello,
I want to implement ACH pay flow service in my website. but i didn't found any proper api documentation
I am new in paypal integration. can you please help me to resolve this.
Also please let me know how to implement ACH in my website. I also create account in manager.paypal.com
How can we set payment method on checkout page. like using ACH , credit card, debit card, check etc.

Thank you.

**Comment by pp-randy** [comment]
Please see the following comment https://github.com/paypal/PayPal-PHP-SDK/issues/843#issuecomment-300193519.

Payflow Support ACH but I believe it needs to be approved by a sales department.
