### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Octolus** [paypal/merchant-sdk-php#147]
curl -k -L https://raw.githubusercontent.com/paypal/merchant-sdk-php/stable-php5.3/samples/install.php | php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     73      0 --:--:-- --:--:-- --:--:--    73
404: Not Found

**Comment by jaypatel512** [comment]
Hey @Octolus !

We recommend you use [composer](https://getcomposer.org/doc/01-basic-usage.md) to install all your php dependencies, including `merchant-sdk-php`. It is now a defacto standard, and is used widely across all php packages. 

We will update our README with proper instructions soon. Thanks for pointing that out. Please re-open this issue if you have trouble installing this package using composer.
