### ISSUE TITLE
Please create new release with latest fixes

### ISSUE THREAD

**Issue by ctipggroup** [paypal/merchant-sdk-php#152]
### General information

* SDK/Library version: v3.11.0
* Environment: Production
* Language, language version, and OS: PHP

### Issue description

Please create a new release including all changes made after v3.11.0. I'm trying to get the fix for https://github.com/paypal/merchant-sdk-php/commit/0ac6c2c084750ff1b4dec0a668edfa0e9acaf01d using composer without reverting to using an earlier version.

Thanks

**Comment by xiaoleih41** [comment]
We are working on this.

**Comment by bluk** [comment]
[v3.12.0](https://github.com/paypal/merchant-sdk-php/releases/tag/v3.12.0) was released yesterday. Thanks for your patience.
