### ISSUE TITLE
Can not force users to pay without need of paypal registration but using credit card only

### ISSUE THREAD

**Issue by Bgcreate** [paypal/merchant-sdk-php#155]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Hi there,
Despite that i am setting the following lines bellow it still redirects some of the users to the paypal signup page instead of the guest checkout page where you can pay without registration. Is there any way to force the clients to always be redirected to the guest checkout page. I am testing it with the exact same selected currency and country with/without cleared cookies and behave differently. 
$setECReqDetails->LandingPage        = 'Billing';
$setECReqDetails->SolutionType        = 'Sole';

**Comment by xiaoleih41** [comment]
Guest checkout is only for new users who do not have PayPal account. You cannot force people to use guest checkout if they already have a PayPal account. Once they hit certain usage threshold, login into their account will be the only option.
