### ISSUE TITLE
SSL peer handshake failed

### ISSUE THREAD

**Issue by factorin-j** [paypal/merchant-sdk-php#156]
<img width="1049" alt="screen shot 2018-05-26 at 11 37 07 pm" src="https://user-images.githubusercontent.com/2919310/40577820-c588b8a2-613d-11e8-9601-d4079971187e.png">
I installed this to symfony via composer but I always get SSL error. 
Is there any settings that should be configured for this to work?

**Comment by theyough** [comment]
i get the same error

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
