### ISSUE TITLE
Deprecation Warning on Composer v1.10.0

### ISSUE THREAD

**Issue by james-mckinnon** [paypal/merchant-sdk-php#161]
### General information

* SDK/Library version: 3.12.0
* Environment: Both
* Language, language version, and OS: PHP v7.4.3 on Ubuntu 19.10

### Issue description

I updated Composer to it's most recent version earlier (v1.10.1) and have been getting a deprecation warning ever since:
```
Deprecation Notice: Class PayPal\EBLBaseComponents\BillingPeriodDetailsType_Update located in ./vendor/paypal/merchant-sdk-php/lib/PayPal/EBLBaseComponents/BillingPeriodDetailsType_Update.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```
I've looked through the release notes on Composer and found that they added the deprecation warning in [v1.10.0](https://github.com/composer/composer/releases/tag/1.10.0).

As it says that the class will no longer be autoloaded in v2 of Composer, I thought I should let you know :)

**Comment by victormln** [comment]
If you're interested on solve this, you have here a PR: https://github.com/paypal/merchant-sdk-php/pull/163

**Comment by jaypatel512** [comment]
Hey @james-mckinnon ! 

You are absolutely right. We may have to create a new class and deprecate this class to make sure it is backward compatible. @victormln I see that in your PR you have renamed the class. I believe this may cause older integration to fail if we merge this and release, unless we do a major release with new version. Thoughts ?

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
