### ISSUE TITLE
what's the redirect-url for live?

### ISSUE THREAD

**Issue by mercuryPP** [paypal/merchant-sdk-php#165]
the ExpressCheckout sample work great for sandbox environment.

Just wondering if I wanna it **go live**, what is the redirect-url($payPalURL)?

SetExpressCheckout.php    line 195:
		`$payPalURL = 'https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=' . $token;`

DGSetExpressCheckout.php     line 121:
	`echo "<br><br><br><br><br><br><br><br><a href=https://www.sandbox.paypal.com/incontext?token=$token />Click here to continue to https://www.sandbox.paypal.com/incontext?token=$token</a>";`

**Comment by devchristina** [comment]
Closing due to lack of support, repo will be archived.
