### ISSUE TITLE
Usage of sdk-core-php results in E_DEPRECATED warnings

### ISSUE THREAD

**Issue by stilliard** [paypal/merchant-sdk-php#166]
### General information

* SDK/Library version: latest
* Environment: production

### Issue description

Hey :wave:

This repo uses [paypal/sdk-core-php](https://github.com/paypal/sdk-core-php) in the [composer file](https://github.com/paypal/merchant-sdk-php/blob/master/composer.json#L16) which appears to be deprecated / archived by paypal. 

As this repo isn't yet marked as deprecated / archived, is there any way to get a fix made to sdk-core-php as it's used here and both are under the paypal account? 

It's causing `E_DEPRECATED: Cannot use "parent" when current class scope has no parent` warnings in production, ref https://github.com/paypal/sdk-core-php/issues/118

Thank you.

**Comment by hahazyb201** [comment]
When will this pull request be merged into the paypal/sdk-core-php? https://github.com/paypal/sdk-core-php/pull/117 . I am having the same issue which breaks my unit tests in php 7.4.

**Comment by negotiamini** [comment]
same here,  guess we're on our own!

**Comment by BafS** [comment]
We did a fork there: https://github.com/ProtonMail/sdk-core-php

Available on packagist too: https://packagist.org/packages/protonlabs/paypal-sdk-core-php

**Comment by pyrou** [comment]
ping @bluk (as you are the last known merger of the paypal/sdk-core-php repo)

**Comment by bluk** [comment]
@pyrou Sorry, I have not worked at PayPal for some time. My recommendation is to contact PayPal technical support ( https://developer.paypal.com/support/ ).

**Comment by stilliard** [comment]
Hi @bluk, 
Thanks anyway.

For anyone else on this thread or finding this later:

I reached out to PayPal technical support, thinking maybe the current devs are busy working on other projects atm.
Here's their reply:

> Thank you for contacting Merchant Technical Support. 
> 
> I understand that you are proposing a revision to the PayPal PHP SDK due to changes within PHP version 8; sorry for any confusion surrounding this. Per the information at https://github.com/paypal/merchant-sdk-php :
> 
> ![image](https://user-images.githubusercontent.com/77454/99458670-ce33e100-2924-11eb-9eca-e07dd3d5cce1.png)
> 
> I see that there was a recent comment in the github issues link where one of the contributors believes that our team may be able to assist, but our team does not make contributions to the SDKs. Rather, it is the role of PayPal's Merchant Technical Support team to troubleshoot and/or escalate when merchants are encountering errors/outages within PayPal's servers (not at the merchant's local end), and that we do not assist in making changes to the various SDKs.
> 
> I would recommend continuing to post at https://github.com/paypal/merchant-sdk-php/issues where hopefully one of the other contributors will be able to assist. As this issue is not related to a technical issue occurring within the servers at PayPal's end, I am proceeding to close this case.
> 
> Thank you,
> Richard
> Merchant Technical Services

They closed off the ticket, I replied asking if there's anyone they can send the request onto but as it's closed I'm not expecting a reply. Feel free for anyone else to try chasing up too.  

Think for now the best option is to use a Fork such as the one @BafS mentioned.

**Comment by devchristina** [comment]
Closing due to lack of support
