### ISSUE TITLE
PayPal error code 10626 (Transaction refused due to risk model)

### ISSUE THREAD

**Issue by KhaiNQ9x** [paypal/merchant-sdk-php#169]
This issue seems just appeared lately as it worked fine before.
I am not sure whats missing in the code.

I keep getting an error with Sanbox mode:

PayPal\PayPalAPI\DoDirectPaymentResponseType Object
(
    [Amount] => PayPal\CoreComponentTypes\BasicAmountType Object
        (
            [currencyID] => USD
            [value] => 900.00
        )

    [AVSCode] => 
    [CVV2Code] => 
    [TransactionID] => 
    [TransactionPendingReason] => 
    [PendingReason] => 
    [PaymentStatus] => 
    [FMFDetails] => 
    [ThreeDSecureResponse] => 
    [PaymentAdviceCode] => 
    [Timestamp] => 2021-05-05T04:14:47Z
    [Ack] => Failure
    [CorrelationID] => 1e05b5929e12c
    [Errors] => Array
        (
            [0] => PayPal\EBLBaseComponents\ErrorType Object
                (
                    [ShortMessage] => Risk
                    [LongMessage] => Transaction refused due to risk model
                    [ErrorCode] => 10626
                    [SeverityCode] => Error
                    [ErrorParameters] => 
                )

        )

    [Version] => 204.0
    [Build] => 55025969
)

**Comment by devchristina** [comment]
Closing due to lack of support.
