### ISSUE TITLE
Can't change subscription BillingPeriod

### ISSUE THREAD

**Issue by vicn1222** [paypal/merchant-sdk-php#170]
I follow example on UpdateRecurringPaymentsProfile.php and found that the BillingFrequency and BillingPeriod won't change.

The original subscription is monthly payment at $10/month.

Now I want to change to each 12 months at $100. The amount is changed, but it still charges on monthly basis, not 12 months.

Bellow is the code

    $paymentBillingPeriod =  new BillingPeriodDetailsType;
    $paymentBillingPeriod->BillingFrequency = 12;
    $paymentBillingPeriod->BillingPeriod = "Month";
    $paymentBillingPeriod->Amount = new BasicAmountType( "USD", 100 );

I went ahead and try to manually change the subscription inside my paypal or sandbox accounts. In the "Update Pricing" page, the  "Subscription period" is grayed out.

Can someone tell me what do I do wrong?

Thanks.

**Comment by devchristina** [comment]
Closing due to lack of support.
