### ISSUE TITLE
Is PayPal NVP/SOAP API Down? Unable to Invoke CreateRecurringPaymentsProfile Method.

### ISSUE THREAD

**Issue by kuldiph** [paypal/merchant-sdk-php#172]
We have tried PayPal Technical Support but have not heard back or they just close out our case. 

### General information

* SDK/Library version: Postman
* Environment: Both Sandbox and Production
* `PayPal-Debug-ID` values: 
* PayPal MTS Case Number 09711379

### Issue description

Unable to Invoke CreateRecurringPaymentsProfile and other methods using NVP/SOAP API. We are seeing 501 Errors. 
![image](https://user-images.githubusercontent.com/19719474/140802352-ace2512f-012e-48dc-8efc-c761a90cc2e6.png)

**Comment by fenix20113** [comment]
Hi, is there any update on this? I am getting the same error.

**Comment by devchristina** [comment]
@fenix20113 apologies for any issues, we're closing this pr due to lack of support. If you're still facing issues please submit a ticket with [Merchant Technical Support](https://www.paypal-support.com/s/?language=en_US).
