### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by uuf6429** [paypal/merchant-sdk-php#175]
Is this SDK/library still active?

The [wiki](https://github.com/paypal/sdk-core-php/wiki/Configuring-the-SDK) links point to a deprecated project (sdk-core-php), doc links are broken and the last updates to this repository are from years ago.

Additionally, the PayPal Developer Center doesn't mention this SDK and at the same time this SDK seems to be using SOAP, while the Dev Center is all about REST APIs... what is going on???

On a more realistic note: I can't get the configuration properly set up - the documentation and example mention a username and password pair, whereas the sandbox provides a client id and secret.

**Comment by patie** [comment]
@uuf6429 no its not, this SDK handle deprecated API and its not available for new customers. You should use new API which doesnt have official PHP SDK under active development at this moment.

**Comment by devchristina** [comment]
Apologies for the challenges this unmanaged repo has created, we're officially archiving this repo and closing the open PRs.
