### ISSUE TITLE
ShippingDiscount and InsuranceTotal do not get carried to GetTransactionDetails object.

### ISSUE THREAD

**Issue by kenjohnson** [paypal/merchant-sdk-php#19]
I am using SDK 98, Express Checkout, PHP

**problem**
 Set $paymentDetails->ShippingTotal and
     $paymentDetails->InsuranceTotal,  do a DoDirectPayment,
     grab the transaction id, and call getTransactionDetails. In getTransactionDetails response object, ShipDiscount and InsuranceAmount are not set. 

**Reproduce by:**
step 1. 
  go to samples/DirectPayment
  modify DoDirectPayment.php to add the 
  following to the paymentDetails object:
  ItemTotal, ShippingTotal, ShippingDiscount, 
  InsuranceTotal. You would also need to modify
  the OrderTotal. It would look something like this.

```
$paymentDetails->ItemTotal = new BasicAmountType('USD', $_POST['amount']);

$paymentDetails->ShippingTotal = new BasicAmountType('USD', 2.00);

$paymentDetails->ShippingDiscount = new BasicAmountType('USD', -1.60);

$paymentDetails->InsuranceTotal = new BasicAmountType('USD', 1.40);

$paymentDetails->OrderTotal = new BasicAmountType('USD', $paymentDetails->ItemTotal + $paymentDetails->ShippingTotal->value  + $paymentDetails->ShippingDiscount->value + $paymentDetails->InsuranceTotal->value);
```

step 2.
   run the program. Notice that the paymentDetails objects are all set correctly. Good so far. 

step 3. 
  Down at the bottom, after this code:

```
  echo "<pre>";
  print_r($doDirectPaymentResponse);
  echo "</pre>";
```

  Add some code here to call GetTransactionDetails
  using the transaction id you just got
  ($doDirectPaymentResponse->TransactionID)

step 4.
   run it. 

**results:**

  Observe the GetTransactionDetails response object. 
  Notice that ShipDiscount and InsuranceAmount are
  not set.  Also notice that ShipAmount is not a 
  BasicAmountType object here; it was back in PaymentDetails when we defined it. 
  Here are some snippets from that object. 

```
                    [ShipAmount] => 2.00
                    [ShipHandleAmount] => 0.00
                    [ShipDiscount] => 
                    [InsuranceAmount] =>

                    [GrossAmount] => BasicAmountType Object
                        (
                            [currencyID] => USD
                            [value] => 2.80
                        )
```

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue. Please update the SDK to latest version.
