### ISSUE TITLE
Add "CreateBillingAgreement" example

### ISSUE THREAD

**Issue by RamyTalal** [paypal/merchant-sdk-php#41]
Add "CreateBillingAgreement.php" and "CreateBillingAgreement.html.php" examples to `samples/BillingAgreements`.

**Comment by hjr3** [comment]
@whit1206 :heart_eyes: thanks for writing this up

**Comment by dhirnitish** [comment]
I am trying to get a BAID and i need to pass ACTION=X. Is there anyway i can do it using the above reference?

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
