### ISSUE TITLE
Google app engine : Curl module is not available on this system

### ISSUE THREAD

**Issue by akashiyu** [paypal/merchant-sdk-php#49]
I am using a php sdk and I get this error message "Curl module is not available on this system" on local dev_appserver, I found that there is no support for curl in app engine.
https://github.com/paypal/merchant-sdk-php/wiki/SDK-Configuration-Parameters
http.GoogleAppEngine=false is only for java apps so how am I support to use php sdk in app engine ?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
