### ISSUE TITLE
Cannot update recurring payments profile Billing Period

### ISSUE THREAD

**Issue by ahc2483** [paypal/merchant-sdk-php#51]
When using the code from the sample for UpdateRecurringPaymentsProfile to update the BillingPeriod details on an existing recurring payments profile, the updated BillingPeriod isn't actually persisted on the profile. Retrieving the recurring payments profile's details yields the previous BillingPeriod.

**Comment by pp-randy** [comment]
The details that can be updated are here: https://developer.paypal.com/docs/classic/api/merchant/UpdateRecurringPaymentsProfile_API_Operation_NVP/

Billing cycles can be changed, but not the frequency.
