### ISSUE TITLE
Samples Not Working

### ISSUE THREAD

**Issue by rmevans1** [paypal/merchant-sdk-php#68]
When I try to run the samples I get this error message:

Fatal error: Access to undeclared static property: PPBaseService::$SDK_NAME in /var/www/robertevansmb/paypal/vendor/paypal/merchant-sdk-php/samples/vendor/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceServiceService.php on line 22

**Comment by krewmarco** [comment]
Are you using Docker?  I found this helpful:
https://github.com/docker-library/php/issues/133

**Comment by engharb** [comment]
I have installed the paypal sdk. everything works well only when I start calling class DoExpressCheckoutPaymentRequestDetailsType
I get the following message:

Class 'DoExpressCheckoutPaymentRequestDetailsType' not found

I tried to call the class by include_once also the same problem.

It will be kind of you responding soon.

Regards,

**Comment by xiaoleih41** [comment]
Merchant SDK is older version of PayPal SDK. Please look into PayPal REST SDK for the newest version of PayPal SDK.
