### ISSUE TITLE
Refused to display https://www.paypal.com/au/cgi-bin' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

### ISSUE THREAD

**Issue by sndelhi3188** [paypal/merchant-sdk-php#70]
Refused to display https://www.paypal.com/au/cgi-bin' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN',
Plz suggest for a alternate soluton.

**Comment by jaypatel512** [comment]
This question does not seem to be related to Merchant SDK. Please re-open this issue, and please add more information if possible for further assistance.
