### ISSUE TITLE
Get transaction details from pay-key

### ISSUE THREAD

**Issue by ShindeSatish** [paypal/merchant-sdk-php#77]
I need to get transaction details from pay-key. Is there any method like PaymentDetailsRequest() in this SDK.

**Comment by PriyankaAwachat** [comment]
I need to get transaction details from pay-key. Is there any method like PaymentDetailsRequest() in this SDK.

**Comment by pp-randy** [comment]
@PriyankaAwachat the SDK you are looking for is https://github.com/paypal/adaptivepayments-sdk-dotnet.

**Comment by pp-randy** [comment]
Locking this thread, please use the adaptivepayments-sdk repositories for Adaptive Payment SDK assistance.
