### ISSUE TITLE
Paypal recurring payments

### ISSUE THREAD

**Issue by sachy123** [paypal/merchant-sdk-php#79]
On paypal website I am asked to download the merchant sdk
https://devtools-paypal.com/guide/recurring_payment_ec/php?env=sandbox
and I downloaded it from here https://github.com/paypal/merchant-sdk-php

but , when i run the $paypalService=new PayPalAPIInterfaceServiceService(Yii::app()->Paypal);
I got a lot of errors on missing files from the library e.g PPBaseService.php was missing the merchant SDK.

So I had to download the core SDK  from here : https://github.com/paypal/sdk-core-php
and copy those missing library files.

Now when everything works well, 
I recieved the error below

``` php
array_merge(): Argument #2 is not an array 
 */
106     private function getConfigHashmap()
107     {
108         return $this->config;
109     }
110     
111     /**
112      * use  the default configuration if it is not passed in hashmap
113      */
114     public static function getConfigWithDefaults($config=null)
115     {
116         return array_merge(PPConfigManager::$defaults, 
117                 ($config != null) ? $config : PPConfigManager::getInstance()->getConfigHashmap());
118     }
119 }
```

**Comment by talss89** [comment]
We are experiencing this issue in v2.5.9 installed via composer. The issue occurs when running a lightly modified version of this example: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

**Comment by walshy002000** [comment]
This is still happening on 3.3.0

**Comment by jaypatel512** [comment]
Hey @talss89 !

The sample that you are trying to do, should not be using this SDK. Please use https://github.com/paypal/PayPal-PHP-SDK for the given sample.

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
