### ISSUE TITLE
GetTransactionDetails and Reversed Transactions

### ISSUE THREAD

**Issue by MavenSean** [paypal/merchant-sdk-php#86]
Prior to issuing a refund for a transaction, I am performing a GetTransactionDetails to ensure that the transaction has not already been refunded and is in either a Completed or Partialy-Refunded state.

When however a Reversed or Refunded status come up, I need to record the unique transaction id of the reversal transaction or refund transaction.

Is there a way to get the reversal or refund details?  Specifically the unique transaction id of the actual reversal or refund.

**Comment by kzap** [comment]
do a TransactionSearch with TransactionID set to the Parent/Original Transaction ID
and it will return reversed and refunded transactions related to that one.

just note there are quirks where the Search results will have different transaction status or type than the actual GetTransactionDetails Result, its very annoying

**Comment by pp-randy** [comment]
Thank you for providing an answer for this issue @kzap.
