### ISSUE TITLE
TaxAmount on RefundRequestTransactionType missing?  Also calculated refund on response is very far off?

### ISSUE THREAD

**Issue by MavenSean** [paypal/merchant-sdk-php#87]
I'm attempting to do an API refund on a transaction.  Full refunds are going through just fine, partial refunds periodically seem to fail.  It appears the culprit is such:

We issue a refund for an amount of 258.50 (This is the amount on the BasicAmount object.
We send the refund request to PayPal, and receive a response with the following breakdown:

NetRefundAmount: 251.01
FeeRefundAmount: 7.49
GrossRefundAmount: 258.50 (The correct amount)
TotalRefundAmount: 273.07

The currency all the way through is in USD.

**Comment by MavenSean** [comment]
Insight into this issue would be extremely helpful :)

**Comment by jaypatel512** [comment]
Hey @MavenSean ! Let me try to reproduce this in my machine, and get back to you. I will let you know as soon as possible, if I could find the root cause of this issue.

**Comment by MavenSean** [comment]
Thanks Jay, much appreciated as I've been banging my head against a wall on this one. ;)

**Comment by jaypatel512** [comment]
Hey @MavenSean ! I just tried to reproduce the issue using samples. I was getting the same Total Refund as Gross Refund. Do you have a sample or code block that I could use to replicate this ? 

Is this behavior intermittent ? or does this happen on any specific combination of amount ? 

![screen shot 2015-01-21 at 11 19 06 am](https://cloud.githubusercontent.com/assets/1309895/5841051/8531c812-a15f-11e4-8b7b-b9195f1ee974.png)

**Comment by MavenSean** [comment]
This may not actually be an issue rather a lack of clarification on the documentation with the API. :)

The TotalRefundAmount reflects the amount refunded PERIOD.  So if you do a partial refund, then subsequently do another refund the TotalRefundAmount will reflect the amount refunded in the current refund PLUS the previous partial refund.

**Comment by MavenSean** [comment]
Thank you for looking into this Jay

**Comment by jaypatel512** [comment]
AAaaah !! Got it now. So, lets say, you do $5 refund first, and then $250, the totalRefund would be $255 when it comes back. Agreed. Probably a lack of documentation. Adding something like "reflects total of all refunds done on this transaction" or something similar would help. 

I will create a documentation issue, and see if they feel to add more information about this, however, feel free to re-open if you think this is still an issue.
