### ISSUE TITLE
Sample triggers Fatal error: require(): Failed opening required 'PPAutoloader.php' 

### ISSUE THREAD

**Issue by ricardo-lewis** [paypal/merchant-sdk-php#88]
This is in the file samples/ExpressCheckout/SetExpressCheckout.php using version 3.8.107.

There doesn't seem to be any PPAutoloader.php file included in the SDK?

**Comment by anil3a** [comment]
I also got the same error when loading sample files:

Fatal error: require(): Failed opening required 'PPAutoloader.php'  in merchant-sdk-php-3.8.107\samples\PPBootStrap.php on line 21

I saw the MASTER branch has the file but this release has no file included.

**Comment by jaypatel512** [comment]
PPAutoloader file is generated by `install.php`. this is an alternate way of installing all the dependencies. Our recommended option would be to use composer for any dependency management, which should remove your need for PPAutoloader.php.
