### ISSUE TITLE
Misleading usage of NotifyURL in SetExpressCheckout.php ExpressCheckout-Example

### ISSUE THREAD

**Issue by jeff1985** [paypal/merchant-sdk-php#89]
I'm referring to the the documentation located here: https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_SOAP/

> Important: The notify URL applies only to DoExpressCheckoutPayment. 
> This value is ignored when set in SetExpressCheckout or GetExpressCheckoutDetails.

In the file samples/ExpressCheckout/SetExpressCheckout.php the parameter is set from the request data, which is wrong and misleading.

``` php
if(isset($_REQUEST['notifyURL']))
{
    $paymentDetails->NotifyURL = $_REQUEST['notifyURL'];
}
```

I also have verified, that setting NotifyURL only in SetExpressCheckout stage does not have any effect, the parameter is simply ignored. You really need to set it in DoExpressCheckoutPayment, otherwise no IPN will be delivered.

My suggestion is to remove those lines from SetExpressCheckout.php

**Comment by peter-parkerr** [comment]
@jeff1985 
Hi, I've tried  to set NotifyURL in DoExpressCheckout method. But still no IPN delivered. 
while the IPN call back URL is working fine on IPN simulator 
Can you please help me to resolve this.
Thanks

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
