### ISSUE TITLE
ExpressCheckout: optional parameter AllowNote will be lost, if set to integer 0

### ISSUE THREAD

**Issue by jeff1985** [paypal/merchant-sdk-php#90]
The parameter AllowNote appears to be datatype sensitive.

The following code will NOT transfer any value for AllowNote in the SOAP message. In this case, "1" is the default value, so the user will be able to enter a note in the checkout process. 

``` php
$setECReqDetails->AllowNote = 0;
```

Only if the value is set to a string "0", the value will be transferred in the SOAP message and will work as intended. The effect will be, that the user is not able to enter a note in the checkout process,

``` php
$setECReqDetails->AllowNote = "0";
```

I would expect at least a log warning, when ignoring parameters, or just support the integer 0.

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
