### ISSUE TITLE
Uncaught exception 'PPConfigurationException'

### ISSUE THREAD

**Issue by seoungyu** [paypal/merchant-sdk-php#91]
Hi, 
I am pretty new to Paypal Paypal REST API and got this error:
```
Fatal error: Uncaught exception 'PPConfigurationException' with message 'Config file C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\..\config\sdk_config.ini not found' in C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\PPConfigManager.php:40 Stack trace: #0 C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\PPConfigManager.php(23): PPConfigManager->load('C:\\Users\\Felix\\...') #1 C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\PPConfigManager.php(30): PPConfigManager->__construct() #2 C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\PPLoggingManager.php(43): PPConfigManager::getInstance() #3 C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(49): PPLoggingManager->__construct('PayPal\\Auth\\OAu...') #4 C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\modules\paypa in C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\vendor\paypal\sdk-core-php\lib\PPConfigManager.php on line 40
```
My composer.json:
```json
{
	"require": {
    "php": ">=5.3.0",
    "ext-curl": "*",
    "ext-json": "*",
    "paypal/rest-api-sdk-php" : "0.5.*"
}
```
}
My php file:
```
$loader = require dirname(__DIR__) . '/vendor/autoload.php';

use PayPal\Auth\OAuthTokenCredential;

$oauthCredential = new OAuthTokenCredential("AfKTjU25T18mWKVv8yJthgwHcXwI1OigiOd28qb56GT95HTmFmsqnCrRtLRhptlqZu1ZrV2e721r-QWI", "EKz5gTnp33lrAE9hbycS5nLa50R3tgipIEt0IoTLS9_zSLeSOoa8NjolClt6e2iXzaSAm4iPEVMaeWO_");

$accessToken     = $oauthCredential->getAccessToken(array('mode' => 'sandbox'));
```
Thank you,

**Comment by jaypatel512** [comment]
Can you please make sure if you have set `PP_CONFIG_PATH` properly. Just add this at the top of the location.

```php
define('PP_CONFIG_PATH', dirname(__FILE__));
```

**Comment by seoungyu** [comment]
$loader = require dirname(__DIR__) . '/vendor/autoload.php';
define("PP_CONFIG_PATH", __DIR__);

It still says config file not found with message 'Config file C:\Users\Felix\Documents\Unnamed Site 2\felixinca.com\modules/sdk_config.ini not found' 

 Should I change the path manually?

**Comment by seoungyu** [comment]
I think I am having issue with composer. It keeps saying “failed to open stream”.
I installed composer globally using installer.exe on windows and ran $ composer install.
Or maybe issues with XAMPP path setting....

**Comment by seoungyu** [comment]
Okay so I ended up specify the path and now it seems working. i.e. define("PP_CONFIG_PATH", '..\vendor\paypal\sdk-core-php\tests');

**Comment by jaypatel512** [comment]
Btw, If you are trying to use [PayPal REST APIs](https://developer.paypal.com/webapps/developer/docs/api/), you might be looking for [PayPal-PHP-SDK for REST API](http://paypal.github.io/PayPal-PHP-SDK/).

However, if you are trying to use [Classic APIs](https://developer.paypal.com/webapps/developer/docs/classic/api/), you are in the right place.
