### ISSUE TITLE
Customer name on paypal dashboard blank.

### ISSUE THREAD

**Issue by kingkarki** [paypal/merchant-sdk-php#92]
I am using this sdk to create recurring profiles. Everything works good but it shows subscriber name blank on paypal dashboard. 
Please see the attachment for detail. Tomorrow is the deadline of my project so please help me to fix it asap.

Thanks,
Krishna

![screen shot 2015-03-29 at 7 53 13 pm](https://cloud.githubusercontent.com/assets/756162/6885967/44e4b7ce-d64d-11e4-86b6-9f70460de4d5.png)

![screen shot 2015-03-29 at 7 52 29 pm](https://cloud.githubusercontent.com/assets/756162/6885960/2c9020d2-d64d-11e4-9630-7ba6ae9a9460.png)

**Comment by denismachado** [comment]
Im facing the same issue. Did anybody get around it?

**Comment by tomwhipple** [comment]
@denismachado Unfortunately I'm not responsible for this product anymore... I'd recommend you reach out to support for a quicker answer: https://www.paypal-support.com/

**Comment by devchristina** [comment]
Closing due to lack of support, this repo will be archived.
