### ISSUE TITLE
Fatal error: Uncaught exception 'PPConnectionException' with message 'Unknown cipher in list: TLSv1' in .../PPHttpConnection.php:91 

### ISSUE THREAD

**Issue by sujansh** [paypal/merchant-sdk-php#94]
Getting above mentioned error on server today, it was working few days back and is still working on my localhost.. not sure, if I am missing something. I tried to search on this topic but couldn't get what exactly the issue is.

Detail error: 

Fatal error: Uncaught exception 'PPConnectionException' with message 'Unknown cipher in list: TLSv1' in .../PPHttpConnection.php:91 
Stack trace: #0 .../merchant-sdk-php-master/vendor/paypal/paypal-sdk-core-php-016a8e4/lib/PPAPIService.php(65): PPHttpConnection->execute('makeRequest('SetExpressCheck...', Object(PPRequest)) #2 .../merchant-sdk-php-master/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceServiceService.php(623): PPBaseService->call('PayPalAPIAA', 'SetExpressCheck...', Object(SetExpressCheckoutReq), Object(PPApiContext), Array) #3 .../_paypal.php(71) in ..../merchant-sdk-php-master/vendor/paypal/paypal-sdk-core-php-016a8e4/lib/PPHttpConnection.php on line 91

Your help is much appreciated!

thanks

**Comment by jaypatel512** [comment]
This issue was caused because of recent POODLE vulnerability found in SSLv3. This issue should have been surfaced by now. 

Can you please make sure that you have TLSv1 installed in your server system. Please ask your hosting provider if that is supported.

**Comment by sujansh** [comment]
yes I just confirmed with the support regarding TLSv1 in our server system. But I am still getting the same issue..

**Comment by jaypatel512** [comment]
Also, can you please make sure you have the version higher than 2.5.8 of paypal/sdk-core-php ?

**Comment by sujansh** [comment]
ah I see what the issue was, my server was using the curl + NSS and as per this link: http://stackoverflow.com/questions/26882530/paypal-sdk-adaptive-payments-unknown-cipher-in-list-tlsv1 I tried commenting out the "CURLOPT_SSL_CIPHER_LIST" in the request. Which worked!!..

anyways, thank you for your time!
