### ISSUE TITLE
SSL certificate problem: Invalid certificate chain

### ISSUE THREAD

**Issue by mjebrini** [paypal/merchant-sdk-php#95]
Switching to live version failed, I am using composer with "paypal/merchant-sdk-php":"2.11.*" 
I get his exception every time I try to do a payment: 

SSL certificate problem: Invalid certificate chain paypal\sdk-core-php\lib\PPHttpConnection.php line 90

```php
	do {
		$result = curl_exec($ch);
		$httpStatus = curl_getinfo($ch, CURLINFO_HTTP_CODE);
	} while (in_array($httpStatus, self::$retryCodes) && (++$retries < $this->httpConfig->getHttpRetryCount()) );
}
if ( curl_errno($ch) ) {
 // line 90 
 $ex = new PPConnectionException($this->httpConfig->getUrl(), curl_error($ch), curl_errno($ch));
  curl_close($ch);
  throw $ex;
} 
```

Am using PHP/OpenSSL/Curl 

PHP cURL with NSS
PHP 5.5
Amazon web hosting service 

The application used to fully work on the sandbox, switching to live resulted this.

**Comment by brickgale** [comment]
Encountered the same bug when mode is in "sandbox". "live" is okay.

**Comment by brickgale** [comment]
fixed my bug on ssl certificate problem. i just override or manually changed the config for `CURLOPT_SSLVERSION` on `PPHttpConfig.php` to 6 so that it will be set to TLSv1.2 since sandbox currently requires it. 

`\PayPal\Core\PPHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = 6;`

**Comment by pp-randy** [comment]
@mjebrini was the comment from @brickgale able to help you resolve your issue as well?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
