### ISSUE TITLE
Namespace conflict with buttonmanager-sdk-php

### ISSUE THREAD

**Issue by rb-cohen** [paypal/merchant-sdk-php#97]
Its not possible to use paypal/buttonmanager-sdk-php and paypal/merchant-sdk-php in the same project.

Both have a PayPal\Service\PayPal\APIInterfaceServiceService class, with different methods in it.

Any chance of forking these classes to their own class name/namespace?

**Comment by nicomollet** [comment]
Same here, the two SDK have different functions useful for my project.

**Comment by jaypatel512** [comment]
Released [Button Manager 4.0.0](https://github.com/paypal/buttonmanager-sdk-php/releases/tag/v4.0.0). Please read the migration guide to use it with merchant SDK.
