### ISSUE TITLE
Problem with namespaces since version 3.9.0

### ISSUE THREAD

**Issue by willy0275** [paypal/merchant-sdk-php#98]
Hello, I was using paypal/merchant-sdk-php (v3.8.107) and everyting was fine but when I did an composer update, I got paypal/merchant-sdk-php (v3.9.0) and paypal/sdk-core-php (v3.1.0) and suddenly I got the following error:

    PHP Fatal error:  Class 'PayPal\Core\PPXmlMessage' not found in /home/atuvu/public_html/paypal/vendor/paypal/merchant-sdk-php/lib/PayPal/EBLBaseComponents/PaymentDetailsType.php on line 9

I checked vendor/composer/autoload_namespaces.php and the namespace for the core sdk completely disappeared!

**Comment by jaypatel512** [comment]
Hey @willy0275 !

We realized the issue. We accidently made a release on non-namespaced branch of SDK Core. I have made another release with [v3.2.0](https://github.com/paypal/sdk-core-php/releases/tag/v3.2.0), with correct namespace. You should be able to resolve those issues now :) 

Thanks for letting us know.

**Comment by willy0275** [comment]
Thank you, I was pulling my non existent hair out for a while last night 
until I realized it was a namespace problem.


Guillaume

**Comment by jaypatel512** [comment]
Sorry for the confusion. Automation had its own flaw :+1:, and we just hit one ! :+1: 

Recently, we made some changes to remove the non-namespaced PHP Core libraries, as we wish to move all merchants to use PHP 5.3 or higher, considering many security fixes that comes in newer versions of PHP.

Thanks for letting us know. Helped save a lot of people's time ! Appreciated.
